version: '3.3'

services:
    postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: camunda
        POSTGRES_PASSWORD: camunda
        POSTGRES_DB: process-engine
        PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata

    camunda:
        image: camunda/camunda-bpm-platform:latest
        container_name: camunda_bpm
        ports:
            - '8080:8080'
        environment:
            DB_DRIVER: org.postgresql.Driver
            DB_URL: jdbc:postgresql://postgres:5432/process-engine
            DB_USERNAME: camunda
            DB_PASSWORD: camunda
            WAIT_FOR: postgres:5432
            WAIT_FOR_TIMEOUT: 60
        depends_on:
            - 'postgres'

    pm4pyws:
        image: javert899/pm4pyws:multiNode
        container_name: pm4pyws
        ports:
          - '80:80'
        volumes:
          - /opt/files:/app/files

    camunda-exporter:
        image: javert899/incremental-camunda-parquet-exporter:latest
        container_name: camunda-exporter
        volumes:
          - /opt/files:/app/files
          - /opt/extraction_consts:/app/extraction_consts
        environment:
          TARGET_HOST: postgres
          TARGET_PATH: /app/files/event_logs
          TIMESTAMP_PATH: /app/extraction_consts/timestamp.dump
          NO_PARTITIONS: /app/extraction_consts/no_part.dump
          POSTGRES_USER: camunda
          POSTGRES_PASSWORD: camunda
          POSTGRES_DB: process-engine
          SLEEP_SCHEDULE: 600
          NUM_EVENTS_PARTITION: 10000
          NUM_EVENTS_CHUNK: 10000
          PM4PYWS_DB_ELOG: /app/files/databases/event_logs.db
        depends_on:
          - 'postgres'
          - 'pm4pyws'
